config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @task = Task.new
    @tasks = Task.all
  end

  def create
    task = Task.new(task_params)
    task.save!
    redirect_to tasks_url, notice: 'タスクを登録しました'
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to tasks_url, notice: 'タスクを削除しました'
  end

  def update
    task = Task.find(params[:id])
    task.update!(task_params)
    redirect_to tasks_url, notice: 'タスクを更新しました'
  end

  def edit
    @task = Task.find(params[:id])
  end

  private

  def task_params
    params.require(:task).permit(:name, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | AppStudy
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

app/views/tasks/edit.html.slim
= form_with model: @task, local: true do |f|
  .form_group
    = f.label :name
    br
    = f.text_field :name
  .form_group
    = f.label :content
    br
    = f.text_area :content
  = f.submit
br
= link_to '一覧', tasks_path

app/views/tasks/index.html.slim
= form_with model: @task, local: true do |f|
  .form_group
    = f.label :name
    br
    = f.text_field :name
  .form_group
    = f.label :content
    br
    = f.text_area :content
  = f.submit
br
table border='1'
  - @tasks.each do |t|
    tr
      td= t.name
      td= t.content
      td= link_to '削除', t, method: :delete, data: {confirm: "タスク#{t.name}を削除していいですか？"}
      td= link_to '編集', edit_task_path(t)